apiVersion: apps/v1
kind: Deployment
metadata:
  name: kata-devops-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kata-devops-python
  template:
    metadata:
      labels:
        app: kata-devops-python
    spec:
      containers:
        - name: kata-app
          image: 99diego/kata-devops-python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
