# .github/workflows/ci.yml
name: CI/CD Python Docker

# Definimos los eventos que disparan el pipeline
on:
  push:
    branches: [ main ]         # Se ejecuta en cada push a main
  pull_request:
    branches: [ main ]         # Se ejecuta en cada PR hacia main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest      # Runner de GitHub

    steps:
    # 1. Checkout del c√≥digo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # 4. Ejecutar tests
    - name: Run tests
      run: pytest -v tests/

    # 5. Login a Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6. Construir imagen Docker
    - name: Build Docker image
      run: docker build -t 99diego/kata-devops-python:latest ./docker

    # 7. Push a Docker Hub
    - name: Push Docker image
      run: docker push 99diego/kata-devops-python:latest

